### ISSUE TITLE
Rate Limiting Error for Threads

### ISSUE THREAD

**Issue by stkbailey** [MeltanoLabs/tap-slack#6]
Received a RateLimited Error when running my last sync:

```
tap-slack-meltanolabs | extractor | time=2021-11-19 11:01:05 name=tap-slack level=INFO message=INFO METRIC: {'type': 'timer', 'metric': 'http_request_duration', 'value'
: 0.012849, 'tags': {'endpoint': '/conversations.replies', 'http_status_code': 429, 'status': 'failed', 'context': {'channel_id': 'C0GJPLE2E', 'thread_ts': '1584125322.
174300'}}}
tap-slack-meltanolabs | extractor | Traceback (most recent call last):
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/bin/tap-slack", line 8, in <module>
tap-slack-meltanolabs | extractor |     sys.exit(TapSlack.cli())
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
tap-slack-meltanolabs | extractor |     return self.main(*args, **kwargs)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
tap-slack-meltanolabs | extractor |     rv = self.invoke(ctx)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/click/core.py",
line 1395, in invoke
tap-slack-meltanolabs | extractor |     return ctx.invoke(self.callback, **ctx.params)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/click/core.py",
line 754, in invoke
tap-slack-meltanolabs | extractor |     return __callback(*args, **kwargs)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/tap_b
ase.py", line 474, in cli
tap-slack-meltanolabs | extractor |     tap.sync_all()
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/tap_b
ase.py", line 343, in sync_all
tap-slack-meltanolabs | extractor |     stream.sync()
W
tap-slack-meltanolabs | extractor |     stream.sync()
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 984, in sync
tap-slack-meltanolabs | extractor |     self._sync_records(context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 927, in _sync_records
tap-slack-meltanolabs | extractor |     self._sync_children(child_context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 989, in _sync_children
tap-slack-meltanolabs | extractor |     child_stream.sync(context=child_context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 984, in sync
tap-slack-meltanolabs | extractor |     self._sync_records(context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 911, in _sync_records
tap-slack-meltanolabs | extractor |     for record_result in self.get_records(current_context):
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/rest.py", line 385, in get_records
tap-slack-meltanolabs | extractor |     transformed_record = self.post_process(record, context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/tap_slack/stream
s.py", line 105, in post_process
tap-slack-meltanolabs | extractor |     self._tap.streams["threads"].sync(context=threads_context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 984, in sync
tap-slack-meltanolabs | extractor |     self._sync_records(context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 911, in _sync_records
tap-slack-meltanolabs | extractor |     for record_result in self.get_records(current_context):
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/rest.py", line 385, in get_records
tap-slack-meltanolabs | extractor |     transformed_record = self.post_process(record, context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/tap_slack/stream
s.py", line 105, in post_process
tap-slack-meltanolabs | extractor |     self._tap.streams["threads"].sync(context=threads_context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 984, in sync
tap-slack-meltanolabs | extractor |     self._sync_records(context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/core.py", line 911, in _sync_records
tap-slack-meltanolabs | extractor |     for record_result in self.get_records(current_context):
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/rest.py", line 384, in get_records
tap-slack-meltanolabs | extractor |     for record in self.request_records(context):
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/rest.py", line 292, in request_records
tap-slack-meltanolabs | extractor |     resp = decorated_request(prepared_request, context)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/backoff/_sync.py
", line 94, in retry
tap-slack-meltanolabs | extractor |     ret = target(*args, **kwargs)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/rest.py", line 205, in _request
tap-slack-meltanolabs | extractor |     self.validate_response(response)
tap-slack-meltanolabs | extractor |   File "/src/data-infrastructure/meltano/.meltano/extractors/tap-slack-meltanolabs/venv/lib/python3.8/site-packages/singer_sdk/strea
ms/rest.py", line 153, in validate_response
tap-slack-meltanolabs | extractor |     raise FatalAPIError(msg)
```

May need to bump up the rate limiting pause for the replies endpoint.

**Comment by stkbailey** [comment]
Should be addressed by https://github.com/MeltanoLabs/tap-slack/commit/fb8b988540c62eaac8e4db97b99d08d65b2766ea
